---
- name: Step 004 Environment specific Software
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
  - name: Print message
    ansible.builtin.debug:
      msg: "Software {{ ACTION | default('provision') }} started for namespace workloads"

- name: Deploy namespaced OpenShift workloads
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
  - name: Apply namespaced workload "{{ workload_loop_var | default('None') }}"
    when: workloads | default([]) | length > 0
    vars:
      ACTION: "{{ ACTION | default('provision') }}"
    ansible.builtin.include_role:
      name: "{{ workload_loop_var }}"
      apply:
        environment:
          K8S_AUTH_HOST: "{{ sandbox_openshift_api_url | default(omit) }}"
          K8S_AUTH_API_KEY: "{{ cluster_admin_agnosticd_sa_token | default('') | trim | default(omit, true) }}"
          K8S_AUTH_VERIFY_SSL: "false"
    loop: "{{ workloads }}"
    loop_control:
      loop_var: workload_loop_var
