---
ai_pull_secret: "{{ ocp4_pull_secret | to_json | to_json if ocp4_pull_secret is mapping else ocp4_pull_secret | to_json }}"
ai_offline_token: "{{ ocp4_ai_offline_token }}"
ai_cluster_name: "{{ guid }}"
ai_ocp_namespace: "{{ sandbox_openshift_namespace | default(config + '-' + guid) }}"

# Container image to use in Ceph cleanup job
ceph_cleanup_job_image: registry.redhat.io/odf4/rook-ceph-rhel9-operator:v4.19
