---
- name: Step 005 Post Software
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
  - name: Entering the test-empty-config post_software.yml
    ansible.builtin.debug:
      msg: Entering the test-empty-config post_software.yml

  - name: Fail the test-empty-config post_software.yml if requested
    when: fail_post_software | bool
    ansible.builtin.fail:
      msg: post_software.yml failed as requested

  - name: Pause post-software
    when: test_empty_config_pause_post_software | default(pause_post_software) | default(false) | bool
    ansible.builtin.pause:
      seconds: "{{ test_empty_config_pause_post_software_seconds | default(30) }}"

  - name: Test agnosticd_user_info from post_software with random string
    when: test_empty_config_passthrough_user_data is undefined
    agnosticd.core.agnosticd_user_info:
      msg: Some random string {{ random_string }}
      data:
        random_string: "{{ random_string }}"
    vars:
      random_string: >-
        {{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}

  - name: Pass-through agnosticd_user_info data
    when: test_empty_config_passthrough_user_data is defined
    agnosticd.core.agnosticd_user_info:
      data: >-
       {{ test_empty_config_passthrough_user_data | from_yaml
       if test_empty_config_passthrough_user_data is string
       else test_empty_config_passthrough_user_data }}

  - name: Test multi-user
    when: test_empty_config_multi_user | bool
    block:
    - name: Test set agnosticd_user_info for users
      when: test_empty_config_passthrough_per_user_data is undefined
      agnosticd.core.agnosticd_user_info:
        user: student{{ n }}
        msg: student{{ n }} password is {{ random_string }}
        data:
          password: "{{ random_string }}"
      loop: "{{ range(1, 1 + test_empty_config_user_count | int) | list }}"
      loop_control:
        loop_var: n
      vars:
        random_string: >-
          {{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}

    - name: Pass-through agnosticd_user_info data for users
      when: test_empty_config_passthrough_per_user_data is defined
      agnosticd.core.agnosticd_user_info:
        user: student{{ n }}
        data: >-
         {{ test_empty_config_passthrough_per_user_data | from_yaml
         if test_empty_config_passthrough_per_user_data is string
         else test_empty_config_passthrough_per_user_data }}
      loop: "{{ range(1, 1 + test_empty_config_user_count | int) | list }}"
      loop_control:
        loop_var: n

    - name: Test add agnosticd_user_info for users
      agnosticd.core.agnosticd_user_info:
        user: student{{ n }}
        data:
          dns_domain: student{{ n }}.example.com
      loop: "{{ range(1, 1 + test_empty_config_user_count | int) | list }}"
      loop_control:
        loop_var: n

  - when: test_empty_config_multiline_secret is defined
    name: Ensure the multiline variable passed as secret is multiline
    ansible.builtin.assert:
      that: test_empty_config_multiline_secret.rstrip().split('\n') | length > 1
      msg: Multiline secret is not multiline

- name: Simulate activity on test hosts
  hosts: testhosts
  gather_facts: false
  tags:
  - step004
  - deploy_software
  tasks:
  - name: Create tempfile
    ansible.builtin.tempfile:
      state: file
    register: r_tempfile

  - name: Populate tempfile with random data
    ansible.builtin.command:
      cmd: >-
        dd
        if=/dev/urandom
        of={{ r_tempfile.path | quote }}
        bs=1k
        count={{ test_empty_config_host_data_size | quote }}

  - name: Slurp tempfile
    ansible.builtin.slurp:
      path: "{{ r_tempfile.path }}"

- name: Step 005 Post Software
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
  - name: Exiting the test-empty-config post_software.yml
    ansible.builtin.debug:
      msg: Exiting the test-empty-config post_software.yml
...
